### ISSUE TITLE
May I please contribute?

### ISSUE THREAD

**Issue by Jxrgxn** [stormpath/stormpath-ios-notes-example#1]
The code is rather pretty. I was hoping I could add to it. I noticed that there are references to string literals, which should deprecate soon. Cheers.

**Comment by edjiang** [comment]
Hey KacheFlowe! 

Thanks for reaching out and asking to help! This is actually going to be a companion repo for a tutorial I'm doing, so definitely meant to be a starting point for you & your projects! I've also published the "finished" version of this tutorial in another branch: 

https://github.com/stormpath/stormpath-ios-notes-example/tree/finished

Here's the backend for this project: 

https://github.com/stormpath/stormpath-express-mobile-notes-example
